"""Capture golden data from the Fortran reference.

Goldens are generated once on a pinned toolchain and committed as plain
.npz, so validation does not depend on a working gfortran on every machine
and does not silently drift when a compiler is upgraded. The toolchain is
recorded in validation/goldens/MANIFEST.md.

Usage::

    uv run python validation/reference/build.py     # build the bridge first
    uv run python validation/capture_reference.py

Re-running on the same toolchain must reproduce the files bit for bit.
"""

from __future__ import annotations

import platform
import subprocess
import sys
from datetime import date
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
GOLDENS = HERE / "goldens"

sys.path.insert(0, str(HERE))
import reference  # noqa: E402

# Temperature sweep, not a single point. The emitted Fortran bakes the
# temperature dependence into per-pair literals plus a piecewise branch
# whose switch point differs for every pair, so a single-temperature check
# would pass with the branch on the wrong side for most pairs.
TEMPERATURES = (250.0, 280.0, 298.15, 320.0)

CS_REF = 1e-3
IPR = 3.0e6

RNG_SEED = 20260908
N_RANDOM_STATES = 20


def capture_rates() -> dict[str, np.ndarray]:
    """K, E and cs across the temperature sweep."""
    out: dict[str, np.ndarray] = {
        "temperatures": np.asarray(TEMPERATURES),
        "cs": reference.get_losses(),
        "fcr": np.asarray(reference.get_fcr()),
    }
    for t in TEMPERATURES:
        k = reference.get_coll(t)
        out[f"K_{t:g}"] = k
        out[f"E_{t:g}"] = reference.get_evap(t, k)
    return out


def capture_rhs() -> dict[str, np.ndarray]:
    """dc/dt for random and structured states.

    Log-uniform over 1e-6 to 1e14 m^-3: the low end is below `negtol` and
    `chtol` (both 1e-6 m^-3, i.e. numerically zero), the high end is well
    above any atmospheric monomer concentration. Spanning that range is what
    catches sign and index errors that a single plausible state hides.
    """
    rng = np.random.default_rng(RNG_SEED)
    states = 10.0 ** rng.uniform(-6.0, 14.0, size=(N_RANDOM_STATES, reference.NEQ))

    # Plus states that exercise specific structure.
    monomers = np.zeros(reference.NEQ)
    monomers[0], monomers[2] = 1e13, 1e15
    structured = np.stack(
        [
            np.zeros(reference.NEQ),  # only the ion sources survive
            monomers,  # vapour only
            np.full(reference.NEQ, 1e12),  # everything populated
        ]
    )
    states = np.concatenate([structured, states])

    out: dict[str, np.ndarray] = {"states": states}
    for t in TEMPERATURES:
        coef = reference.make_coef(t, CS_REF, IPR)
        out[f"dcdt_{t:g}"] = np.stack([reference.feval(c, coef) for c in states])
        out[f"coef_{t:g}"] = coef
    return out


def capture_formation() -> dict[str, np.ndarray]:
    rng = np.random.default_rng(RNG_SEED + 1)
    states = 10.0 ** rng.uniform(4.0, 14.0, size=(10, reference.NEQ))
    coef = reference.make_coef(280.0, CS_REF, IPR)
    results = [reference.formation(c, coef) for c in states]
    return {
        "states": states,
        "coef": coef,
        "j_tot": np.array([r["j_tot"] for r in results]),
        "j_by_charge": np.stack([r["j_by_charge"] for r in results]),
        "j_by_cluster": np.stack([r["j_by_cluster"] for r in results]),
        "j_all": np.stack([r["j_all"] for r in results]),
    }


def capture_rate_coef_tensors() -> dict[str, np.ndarray]:
    """The assembled coefficient tensors -- what the port's RHS must rebuild."""
    out: dict[str, np.ndarray] = {}
    for t in TEMPERATURES:
        coef = reference.make_coef(t, CS_REF, IPR)
        cq, cl = reference.get_rate_coefs(coef)
        out[f"coef_quad_{t:g}"] = cq
        out[f"coef_lin_{t:g}"] = cl
    return out


def _toolchain() -> str:
    try:
        gfortran = subprocess.run(
            ["gfortran", "--version"], capture_output=True, text=True, check=True
        ).stdout.splitlines()[0]
    except (subprocess.CalledProcessError, FileNotFoundError):
        gfortran = "unknown"
    return gfortran


def write_manifest(files: dict[str, int]) -> None:
    lines = [
        "# Golden data manifest",
        "",
        "Generated by `validation/capture_reference.py` from the vendored",
        "Fortran reference. Committed as plain .npz -- no Git LFS.",
        "",
        "Re-running the capture on the toolchain below must reproduce these",
        "files bit for bit. If it does not, something in the reference or the",
        "compiler changed, and that is a finding rather than a nuisance.",
        "",
        "## Toolchain",
        "",
        f"| Compiler | `{_toolchain()}` |",
        "|---|---|",
        "| Flags | `-O3 -fcheck=bounds -finit-local-zero -fallow-argument-mismatch` |",
        f"| Platform | {platform.platform()} ({platform.machine()}) |",
        f"| Python | {platform.python_version()} |",
        f"| NumPy | {np.__version__} |",
        f"| Captured | {date.today().isoformat()} |",
        "",
        "## Conditions",
        "",
        f"- Temperatures: {', '.join(f'{t:g}' for t in TEMPERATURES)} K",
        f"- Reference coagulation sink: {CS_REF:g} 1/s",
        f"- Ion production rate: {IPR:g} 1/m^3/s (equal for both polarities)",
        f"- Random state seed: {RNG_SEED}",
        "",
        "## Files",
        "",
        "| File | Arrays |",
        "|---|---|",
    ]
    lines += [f"| `{name}` | {count} |" for name, count in sorted(files.items())]
    (GOLDENS / "MANIFEST.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    GOLDENS.mkdir(exist_ok=True)
    captures = {
        "rates.npz": capture_rates(),
        "rhs.npz": capture_rhs(),
        "formation.npz": capture_formation(),
        "rate_coef_tensors.npz": capture_rate_coef_tensors(),
    }
    counts = {}
    for name, data in captures.items():
        path = GOLDENS / name
        np.savez_compressed(path, **data)
        counts[name] = len(data)
        size_mb = path.stat().st_size / 1e6
        print(f"wrote {path.relative_to(REPO)}  ({len(data)} arrays, {size_mb:.2f} MB)")
    write_manifest(counts)
    print(f"wrote {(GOLDENS / 'MANIFEST.md').relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
